# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          minor-and-patch:
              update-types:
                  - "patch"
                  - "minor"
          major:
              update-types:
                  - "major"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          minor-and-patch:
              update-types:
                  - "patch"
                  - "minor"
          major:
              update-types:
                  - "major"

    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: "weekly"
      groups:
          github-actions:
              patterns:
                  - "*"
