[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "content"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[pytest]
addopts = [
    "-p no:warnings"
]
