name: Format Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.11.13 djlint==1.36.4 nbstripout==0.8.1

      - name: Install Node dependencies
        run: npm ci

      - name: Check Python formatting with ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Check Django template formatting with djlint
        run: |
          djlint --profile=django --check .

      - name: Check JavaScript/CSS/SCSS/JSON/YAML/Markdown formatting with prettier
        run: npm run fmt-check

      - name: Check Jupyter notebooks are stripped
        run: |
          # Find all Jupyter notebooks and check if they have outputs
          find . -name "*.ipynb" -type f -print0 | xargs -0 -I {} sh -c '
            if nbstripout --verify "$1"; then
              echo "✓ $1 is properly stripped"
            else
              echo "✗ $1 contains outputs that should be stripped"
              exit 1
            fi
          ' _ {}
